# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dantas"
DISABLE_AUTO_UPDATE=true # disables ZSH autoupdate

plugins=(git osx chruby thor)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/alias.sh
source ~/.dotfiles/export.sh
source ~/.dotfiles/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.dotfiles/zsh/history.zsh

# It will enable to use cd -1, cd -2 to go back to previous folders
setopt AUTO_PUSHD

# Init the fasd
eval "$(fasd --init auto)"

# It will do a ls after a cd
function chpwd() {
    emulate -L zsh
    ls
}

# Enables the edition of command lines!
# press cltr+x cltr+e to open the editor and fix any command line errors
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

############################
## FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.dotfiles/zsh/functions/fzf.sh
source ~/.dotfiles/zsh/keybindings.zsh
############################


# To activate these completions
fpath=(/usr/local/share/zsh-completions $fpath)

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/celsodantas/.kube/config:/Users/celsodantas/.kube/config.shopify.cloudplatform
for file in /Users/celsodantas/src/github.com/Shopify/cloudplatform/workflow-utils/*.bash; do source ${file}; done

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

source /Users/celsodantas/Library/Preferences/org.dystroy.broot/launcher/bash/br

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
FZF_DEFAULT_OPTS='-i'

# using ripgrep combined with preview
# find-in-file - usage: fif <searchTerm>
fif() {
  if [ ! "$#" -gt 0 ]; then echo "Need a string to search for!"; return 1; fi
  rg --files-with-matches --no-messages --no-heading "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}" --bind '?:toggle-preview'
}

ff() {
  # rg --color always --line-number --no-heading \"$1\" | fzf --ansi
  # local out file
  # out=("$(rg --color always --line-number --no-heading \"$1\" | fzf --ansi --expect=ctrl-o)")
  read -r file line <<<"$(rg --color always --line-number --no-heading "$@" | fzf --ansi | awk -F: '{ print $1, $2 }')"

  if [[ -n $file ]]; then
    printf "opening %s:%s\n" $file $line
    vim $file +$line
  fi
}
