# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="dantas"
DISABLE_AUTO_UPDATE=true # disables ZSH autoupdate

plugins=(git osx chruby thor)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/alias.sh
source ~/.dotfiles/export.sh
source ~/.dotfiles/vendor/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.dotfiles/zsh/history.zsh

# It will enable to use cd -1, cd -2 to go back to previous folders
setopt AUTO_PUSHD

# Init the fasd
eval "$(fasd --init auto)"

# It will do a ls after a cd
function chpwd() {
    emulate -L zsh
    ls
}

# Enables the edition of command lines!
# press cltr+x cltr+e to open the editor and fix any command line errors
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

############################
## FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.dotfiles/zsh/functions/fzf.sh
source ~/.dotfiles/zsh/keybindings.zsh
############################


# To activate these completions
fpath=(/usr/local/share/zsh-completions $fpath)

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/celsodantas/.kube/config:/Users/celsodantas/.kube/config.shopify.cloudplatform
for file in /Users/celsodantas/src/github.com/Shopify/cloudplatform/workflow-utils/*.bash; do source ${file}; done

[ -f ~/.zshrc.local ] && source ~/.zshrc.local

source /Users/celsodantas/Library/Preferences/org.dystroy.broot/launcher/bash/br
